SELECT *
FROM
(
	SELECT ROWNUM RNUM, A.*
	FROM (
	SELECT 
		BOARD_NO,
		CATEGORY_NAME,
		BOARD_TITLE,
		USER_NO,
		COUNT,
		CREATE_DATE
	FROM BOARD B
	JOIN CATEGORY USING (CATEGORY_NO)
	JOIN MEMBER ON (BOARD_WRITER = USER_NO)
	WHERE BOARD_TYPE = 1
		AND B.STATUS = 'Y'
		ORDER BY CREATE_DATE DESC
		) A
	)
	WHERE RNUM BETWEEN 11 AND 20