--1.
SELECT
    DEPARTMENT_NAME AS "학과 명",
    CATEGORY        AS "계열"
FROM
    TB_DEPARTMENT;
  
--2.
SELECT
    DEPARTMENT_NAME
    || '의 정원은 '
    || CAPACITY
    || '명 입니다.' AS "학과별 정원"
FROM
    TB_DEPARTMENT;
  
--3.
SELECT
    STUDENT_NAME
FROM
    TB_STUDENT
WHERE
        DEPARTMENT_NO = 001
    AND STUDENT_SSN LIKE '_______2%'
    AND ABSENCE_YN = 'Y';
 
--4.
SELECT
    STUDENT_NAME
FROM
    TB_STUDENT
WHERE
    STUDENT_NO IN ( 'A513079', 'A513090', 'A513091', 'A513110', 'A513119' )
ORDER BY
    STUDENT_NAME DESC;
 
--5.
SELECT
    DEPARTMENT_NAME,
    CATEGORY
FROM
    TB_DEPARTMENT
WHERE
    CAPACITY BETWEEN 20 AND 30;

--6.
SELECT
    PROFESSOR_NAME
FROM
    TB_PROFESSOR
WHERE
    DEPARTMENT_NO NOT IN (
        SELECT
            DEPARTMENT_NO
        FROM
            TB_DEPARTMENT
    );

--7.
SELECT
    *
FROM
    TB_STUDENT
WHERE
    DEPARTMENT_NO IS NULL;
 
--8.
SELECT
    CLASS_NO
FROM
    TB_CLASS
WHERE
    PREATTENDING_CLASS_NO IS NOT NULL;
 
--9.
SELECT DISTINCT
    CATEGORY
FROM
    TB_DEPARTMENT
ORDER BY
    CATEGORY;
  
--10.
SELECT
    STUDENT_NO,
    STUDENT_NAME,
    STUDENT_SSN
FROM
    TB_STUDENT
WHERE
        ABSENCE_YN = 'N'
    AND ENTRANCE_DATE LIKE '02%'
    AND STUDENT_ADDRESS LIKE '%전주%';
---------------------------------------------------------------------

--1.
SELECT STUDENT_NO AS "학번",STUDENT_NAME AS "이름",TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') AS 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002 ORDER BY ENTRANCE_DATE; 

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) !=3 ORDER BY PROFESSOR_NAME;

--3.
SELECT PROFESSOR_NAME AS "교수이름", TO_CHAR(SYSDATE,'YYYY')-(SUBSTR(PROFESSOR_SSN,1,2) +1900)  AS "나이" 
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8,1)= 1 ORDER BY PROFESSOR_SSN DESC;

--4.
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) AS "이름"
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE TO_CHAR(ENTRANCE_DATE,'YYYY') - TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RRMMDD'),'RRRR') > 19 ;

--6.
SELECT NEXT_DAY('20201220', '금')
FROM DUAL;

--7.
SELECT TO_DATE('99/10/11', 'YY/MM/DD'), -- 2099/10/11
TO_DATE('49/10/11', 'YY/MM/DD'), -- 2049/10/11
TO_DATE('99/10/11', 'RR/MM/DD'), -- 1999/10/11
TO_DATE('49/10/11', 'RR/MM/DD') -- 2049/10/11
FROM DUAL;

--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) !='A' ORDER BY STUDENT_NO;

--9.
SELECT ROUND(SUM(POINT)/8,1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO AS "학과번호",COUNT(department_no) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12.
SELECT SUBSTR(TERM_NO,1,4) AS "년도",ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113' 
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY SUBSTR(TERM_NO,1,4);


--13.
SELECT DEPARTMENT_NO AS "학과코드명", COUNT(ABSENCE_YN) AS "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO,ABSENCE_YN
HAVING ABSENCE_YN = 'Y'
ORDER BY DEPARTMENT_NO;

--14.
SELECT STUDENT_NAME AS "동일이름", COUNT(STUDENT_NAME) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1
ORDER BY STUDENT_NAME;

--15.
SELECT SUBSTR(TERM_NO,1,4) AS "년도",SUBSTR(TERM_NO,5,2)  AS "학기", ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2))
ORDER BY 1,2;
